version: '3.4'

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:80" 
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=database;Username=postgres;Password=password
      - Cors__AllowedOrigins__0=http://localhost:4500
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure 

  postgres:
    container_name: postgres
    image: postgres:14.3-alpine 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10